### ISSUE TITLE
Zu Rechten

### ISSUE THREAD

**Issue by ReLater** [19leunam93/mod_userlist#1]
Nur als Vorschlag: Das Modul als Modul für's Backend (`client="administrator"`). Dann wäre man evtl. schon ein paar der Sorgen bzgl. Zugriffs-Rechten los.

**Comment by Elfangor93** [comment]
Habe noch nie ein Modul für Backend gemacht. Da muss ich mich erst einlesen...

**Comment by ReLater** [comment]
Eigentlich musst du nur in der XML-Datei `client="site"` mit `client="administrator"` ersetzen. Den Rest erledigt Joomla bei der Installation.

**Comment by Elfangor93** [comment]
Gute Idee!
Dann löst sich auch gleich das Problem von Kurtus. Bei ihm hat im Frontend die Ausgabe nicht geklappt, weil er ein E-Mail Verschleierungs-Plugin einsetzt und dadurch der HTML-Code zur PDF generierung nicht mehr stimmte...
Danke für den Tipp!

**Comment by Elfangor93** [comment]
@ReLater Wie kann ich language strings in Backend-Modulen verwenden?
Ich habe die language files wie folgt eingefügt: 
```XML
<languages folder="language">
        <language tag="en-GB">en-GB/en-GB.mod_userlist.ini</language>
        <language tag="en-GB">en-GB/en-GB.mod_userlist.sys.ini</language>
        <language tag="de-DE">de-DE/de-DE.mod_userlist.ini</language>
        <language tag="de-DE">de-DE/de-DE.mod_userlist.sys.ini</language>
    </languages>
```
In der XML-Datei funktionieren die Langugae strings somit, jedoch in der mod_userlist.php und default.php nicht. Was muss man da noch machen, damit die language files verwendet werden?

**Comment by ReLater** [comment]
Ich verwende immer die bequemere Variante.

Ich füge in dem `<files>`-Block den Ordner `<folder>language</folder>` hinzu, also etwa so:
```
<files>
<filename module="mod_flexsliderghsvs">mod_flexsliderghsvs.php</filename>
<filename>LICENSE.txt</filename>
<folder>fields</folder>
     <folder>language</folder>
<folder>myforms</folder>
<folder>tmpl</folder>
</files>
```

und spare mir das ganze `<languages ...>`-Gedöns (lösche ich).

Die Sprachdateien werden dann nicht in den Joomla-`language`-Ordnern installiert, sondern liegen innerhalb der installierten Erweiterung.

![21-06-_2018_13-06-23](https://user-images.githubusercontent.com/20780646/41715582-3444e52a-7554-11e8-87b2-26bd683f8571.png)

Joomla ist schlau genug auch dort zu suchen. Auch, wenn man Sprach-Overrides macht etc.
Funktioniert mit allen üblichen Arten von Erweiterungen.

Aufpassen muss man nur, dass, wenn in den Joomla-`language`-Ordnern die Sprachdateien ebenfalls liegen (vielleicht von früherer Installation), dass diese dann bevorzugt werden. Also entweder händisch löschen oder erst Erweiterung deinstallieren, damit die dort verschwinden.

**Comment by Elfangor93** [comment]
Das hat geklappt, jedoch ist das Problem das selbe wie davor. Für die Modulkonfiguration (XML-File) werden die language-files verwendet. In den anderen Files nicht:
![grafik](https://user-images.githubusercontent.com/39154009/41717767-191be18e-755b-11e8-894b-2869ddc82df2.png)
Muss in der mod_userlist.php noch eine Zeile wie 
```php
$language = JFactory::getLanguage();
$language->load('mod_userlist');
```
hinzugefügt werden?

**Comment by ReLater** [comment]
Eigentlich nicht. Ich habe das eben mal mit Zeile
`echo JText::_('MOD_LOGGED_FIELD_COUNT_DESC');`

im Backendmodul `mod_logged` ausprobiert (helper.php, mod_logged.php, default.php) auch mit Umverschieben der Sprach-Dateien ins Modul. Und überall wird der Text aus `language/en-GB/en-GB.mod_logged.ini` (also nicht die `.sys.ini`) korrekt ausgegeben. Also 3x zu sehen:

![21-06-_2018_14-12-39](https://user-images.githubusercontent.com/20780646/41718505-74760760-755d-11e8-9178-7a3900d739cc.png)

Vielleicht einen Tippfehler in den Dateinamen? Mein häufigster Fehler.

Es gibt auch einen Debug-Modus für Sprachdateien in der Konfiguration. Vielleicht spuckt der was aus? Glaube am unteren Bildschirmrand (auf der Seite, wo das Modul angezeigt wird am besten).

**Comment by Elfangor93** [comment]
Ich habe natürlich JText::_(...); nicht angewandt -> dann wird auch nichts ersetzt...
Danke für die Hilfe!
